#!/usr/bin/env python

doGUI = True
import sys, os
import BaseHTTPServer

try:
    from Tkinter import *
except:
    print "Cannot load Tkinter. fall back to http server"
    doGUI = False

def log_status(dirName):
    fName = dirName+"/crab.log"
    retVal = (-1,-1,-1)
    if not os.path.exists(fName): return retVal

    jobstatus = {}
    logs = open(fName).readlines()
    for i, l in enumerate(reversed(logs)):
        l = l.strip()
        if 'Looking up detailed status of task ' not in l: continue
        jobstatus = logs[len(logs)-i].strip()
        if not jobstatus.startswith('DEBUG'): continue
        jobstatus = eval('{'+jobstatus.split('{',1)[-1].strip())
        break
    if jobstatus == {}: return retVal

    jobsPerStat = jobstatus['jobsPerStatus']
    nSuccess, nFail = 0,0
    nTotal = sum([int(jobsPerStat[key]) for key in jobsPerStat.keys()])
    if 'finished' in jobsPerStat: nSuccess = int(jobsPerStat['finished'])
    if 'failed' in jobsPerStat: nFail = int(jobsPerStat['failed'])

    return (nSuccess, nFail, nTotal)

##### For the crabmon with HTTP interface
crabItems = {}
commands = ("status", "resubmit", "finish")
def run_command(cmd, crabdir):
    if crabdir not in crabItems:
        print "Cannot find crab dir", crabdir
        return
    if cmd not in commands:
        print "Invalid command", cmd
        return

    if cmd == 'status':
        os.system('crab status %s' % crabdir)
        crabItems[crabdir] = log_status(crabdir)

    elif cmd == 'resubmit':
        os.system('crab resubmit %s' % crabdir)
        run_command('status', crabdir)
    elif cmd == 'finish':
        os.system('crab report %s' % crabdir)
        if not os.path.isdir('done'): os.mkdir('done')
        os.system('mv %s done/' % crabdir)

        del crabItems[crabdir]

class CrabMonHTTP(BaseHTTPServer.BaseHTTPRequestHandler):
    def do_HEAD(s):
        s.send_response(200)
        s.send_header("Content-type", "text/html")
        s.end_headers()

    def do_GET(s):
        s.send_response(200)
        s.send_header("Content-type", "text/html")
        s.end_headers()
        s.wfile.write("""<html>
<head>
<title>Crab Monitor</title>
<style>
table th { text-align:left; color:white; background-color:black;}
</style>
<script>
function disable_all() {
    var inputs = document.getElementsByTagName('input');
    console.log(inputs.Length);
    for ( var i=0; i<inputs.Length; ++i ) {
      console.log(i);
      if ( inputs[i].type != 'submit' ) continue;
      console.log('submit');
      inputs[i].disabled = true;
    }
}
</script>
</head>
<body>""")
        s.wfile.write("<h1>Crab monitoring</h1>")

        ## Parse and run requests
        reqs = {}
        if '?' not in s.path:
            url = s.path
        else:
            url, rr = s.path.split('?', 1)
            for r in rr.split('&'):
                r = r.split('=',1)
                if len(r) == 2: reqs[r[0]] = r[1]
                else: reqs[r[0]] = ''
        if '*' in reqs:
            for item in crabItems:
                run_command(reqs['*'], item)
        else:
            for req in reqs:
                if req not in crabItems:
                    print "Cannot find dir", req
                    continue
                cmd = reqs[req]
                if cmd not in commands:
                    print "Invalid command", cmd
                    continue

                run_command(cmd, req)
        print "@@@ Done"

        s.wfile.write('<form action="/">\n')
        s.wfile.write("<table><tr><th>Name</th><th>nSuccess/nFail/nTotal</th><th>Actions</th></tr>\n")
        for item in sorted(crabItems.keys()):
            crabItems[item] = log_status(item)
            nSuccess, nFail, nTotal = crabItems[item]
            s.wfile.write('<tr><td><!--<input type="checkbox" name="{0}" />-->{0}</td>'.format(item))
            s.wfile.write("<td>%d/%d/%d</td><td>" % (nSuccess, nFail, nTotal))
            if nSuccess == nTotal and nTotal > 0 and nFail == 0:
                s.wfile.write('<input type="submit" name="%s" value="finish" onclick="disable_all();" />' % (item))
            elif nSuccess == nTotal and nTotal > 0 and nFail == -1:
                s.wfile.write('Finished')
            else:
                s.wfile.write('<input type="submit" name="%s" value="status" onclick="disable_all();"/>' % (item))
                if nFail > 0:
                    s.wfile.write('<input type="submit" name="%s" value="resubmit" onclick="disable_all();" />' % (item))
            s.wfile.write('</td></tr>\n')
        s.wfile.write('<tr><td colspan="3">')
        s.wfile.write('<input type="submit" name="*" value="status" onclick="disable_all();"/>')
        s.wfile.write('<input type="submit" name="*" value="resubmit" onclick="disable_all();"/></td></tr>')
        s.wfile.write("</table>\n")
        s.wfile.write("</form>\n")

        s.wfile.write("</body></html>")

## For the crabmon with Tkinter
class CrabMonTkLine:
    def __init__(self, frame, name, size):
        nRow = size % 25 + 1
        nCol = (size / 25)*6
        self.name = name
        self.label = Label(frame, text=name)
        self.label.grid(row=nRow, column=nCol, sticky=W)
        self.statLabel = Label(frame, text="?/?")
        self.statLabel.grid(row=nRow, column=nCol+1, sticky=E)
        self.statusBtn = Button(frame, text="status", command=self.status)
        self.statusBtn.grid(row=nRow, column=nCol+2, sticky=EW)
        self.getBtn = Button(frame, text="get", command=self.get, state=DISABLED)
        self.getBtn.grid(row=nRow, column=nCol+3, sticky=EW)
        self.resubmitBtn = Button(frame, text="resubmit", command=self.resubmit, state=DISABLED)
        self.resubmitBtn.grid(row=nRow, column=nCol+4, sticky=EW)
        self.finishBtn = Button(frame, text="finish", command=self.finish, state=DISABLED)
        self.finishBtn.grid(row=nRow, column=nCol+5, sticky=EW)

        self.status()

    def status(self):
        if not os.path.exists("%s/.requestcache" % self.name): return
        print "@ checking status", self.name
        os.system('crab status %s' % self.name)
        nSuccess, nFail, nJobs = log_status(self.name)
        self.statLabel.configure(text="%d/%d/%d" % (nSuccess, nFail, nJobs))

        if nSuccess > 0:
            self.getBtn['state'] = 'normal'
        if nSuccess == nJobs:
            self.finishBtn['state'] = 'normal'
        if nFail > 0:
            self.resubmitBtn['state'] = 'normal'
        else:
            self.resubmitBtn['state'] = 'disabled'

        print "@ status(%s) done" % self.name

    def get(self):
        if not os.path.exists("%s/.requestcache" % self.name): return
        self.getBtn['state'] = "disabled"
        os.system("crab get %s" % self.name)
        self.getBtn.configure(text="get")
        self.status()
        print "@ get(%s) done" % self.name

    def resubmit(self):
        if not os.path.exists("%s/.requestcache" % self.name): return
        self.resubmitBtn['state'] = 'disabled'
        os.system('crab resubmit %s' % self.name)
        self.status()
        print "@ resubmit(%s) done" % self.name

    def finish(self):
        if not os.path.exists("%s/.requestcache" % self.name): return
        os.system('crab report %s' % self.name)
        if not os.path.isdir('done'): os.mkdir('done')
        os.system("mv %s done/" % self.name)
        self.statusBtn['state'] = 'disabled'
        self.resubmitBtn['state'] = 'disabled'
        self.getBtn['state'] = 'disabled'
        self.finishBtn['state'] = 'disabled'
        self.label.configure(fg='gray')
        self.statLabel.configure(fg='gray')
        print "@ finish(%s) done" % self.name

objs = []
def status_all():
    for obj in objs:
        obj.status()

def resubmit_all():
    for obj in objs:
        obj.resubmit()

if __name__ == '__main__':
    from optparse import OptionParser
    parser = OptionParser()
    parser.add_option("-p", "--port", dest="port", type="int",
                      help="port number", metavar="PORT", default=20000)
    parser.add_option("-n", "--nogui", dest="nogui", action="store_true",
                      default=False, help="do not use Tkinter GUI")
    (options, args) = parser.parse_args()
    options = options.__dict__

    ## Build GUI

    if options["nogui"]: doGUI = False

    if doGUI:
        root = Tk()

        lFrame = Frame(root)
        size = 0
        for d in sorted(os.listdir(".")):
            if d[0] == '.': continue
            if not os.path.isdir(d): continue
            if ".requestcache" not in os.listdir(d): continue

            line = CrabMonTkLine(lFrame, d, size)
            objs.append(line)
            size += 1
        lFrame.pack()

        dFrame = Frame(root)
        allStatusBtn = Button(dFrame, text="status_all", command=status_all)
        allResubmitBtn = Button(dFrame, text="resubmit_all", command=resubmit_all)
        allStatusBtn.pack(side=RIGHT)
        allResubmitBtn.pack(side=RIGHT)
        dFrame.pack()

        root.mainloop()
    else:
        PORT = options["port"]

        for d in os.listdir("."):
            if not d.startswith("crab_"): continue
            if not os.path.isdir(d): continue
            if not os.path.exists(d+'/.requestcache'): continue

            crabItems[d] = [-1,-1,-1]

        print "Starting crabmon web GUI..."
        server = BaseHTTPServer.HTTPServer(("", PORT), CrabMonHTTP)
        print "open http://%s:%d with your web browser" % (os.environ["HOSTNAME"], server.server_address[1])
        try:
            server.serve_forever()
        except KeyboardInterrupt:
            pass

        server.server_close()
        print "Terminate by user"
