#!/usr/bin/env python

import sys, os
sys.argv.append("-b")
from ROOT import *

def dumpRoot(dirRoot, sysPath):
    os.makedirs(sysPath)
    for key in [x.GetName() for x in dirRoot.GetListOfKeys()]:
        obj = dirRoot.Get(key)
        if obj == None: continue
        if obj.IsA().InheritsFrom("TDirectory"):
            dumpRoot(obj, sysPath+"/"+(key.replace(' ', '_')))
        elif obj.IsA().InheritsFrom("TH1"):
            c = TCanvas("c%s" % key, key, 500, 500)
            obj.Draw()
            c.Print("%s/%s.png" % (sysPath, key.replace(' ', '_')))

if __name__ == '__main__':
    fName = sys.argv[1]

    dumpRoot(TFile(fName), os.path.basename(fName[:-5]))


