#!/usr/bin/env python

import sys, os
import json

if len(sys.argv) < 4:
    print "Usage: %s input1.json input2.json output.json" % (sys.argv[0])
    sys.exit(1)

js1 = json.load(open(sys.argv[1]))
js2 = json.load(open(sys.argv[2]))

out = {}
for run in set(js1.keys()).intersection(js2):
    lumis1 = js1[run][:]
    lumis2 = js2[run][:]

    outlumis = []
    while True:
        if len(lumis1) == 0: break
        if len(lumis2) == 0: break
        if lumis2[0][1] < lumis1[0][0]:
            lumis2.pop(0)
            continue
        if lumis1[0][1] < lumis2[0][0]:
            lumis1.pop(0)
            continue

        lumi = [max(lumis1[0][0], lumis2[0][0]), min(lumis1[0][1], lumis2[0][1])]
        outlumis.append(lumi)

        if lumi[1] >= lumis1[0][1]: lumis1.pop(0)
        if lumi[1] >= lumis2[0][1]: lumis2.pop(0)

    if len(outlumis) > 0: out[run] = outlumis[:]

open(sys.argv[3], "w").write(json.dumps(out))
