#!/usr/bin/env python

import sys, os

import subprocess
if subprocess.call("type xrd", shell=True,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE) != 0:
    print "Error: Need xrd command"
    sys.exit()

hostname = os.environ["HOSTNAME"]
cmd = ""
xrdbase = ''
xrdhost = ''
if "sdfarm" in hostname:
    xrdhost = 'cms-xrdr.sdfarm.kr'
    xrdbase = '/xrd'
elif "uos" in hostname:
    xrdhost = 'uosaf0007.sscc.uos.ac.kr'
    xrdbase = '/cms'
else:
    print "Hostname", hostname, "not supported"
    sys.exit()
cmd = "xrd %s ls " % (xrdhost)

dsetIn = []
if len(sys.argv) >= 2:
    dsetIn = [xrdbase+l for l in sys.argv[1:]]
else:
    while True:
        l = raw_input("samples: ").strip()
        if len(l) == 0: break
        if not l.startswith('/'): continue

        dsetIn.append(xrdbase+l)

ds = []
for l in dsetIn:
    fl = []
    size = 0
    dd = set(subprocess.check_output(cmd + l, shell=True).strip().split('\n'))
    for d in dd:
        d = d.strip().split()
        if len(d) == 0: continue
        ff = set(subprocess.check_output(cmd + d[-1], shell=True).strip().split('\n'))

        for f in ff:
            f = f.strip().split()
            if len(f) == 0: continue

            fname = os.path.basename(f[-1])
            if not fname.endswith('.root'): continue
            size += int(f[1])
            fl.append(fname)
    fl.sort()

    path = os.path.dirname(l)
    if path.startswith(xrdbase): path = path[len(xrdbase):]
    ds.append({'path':path, 'files':fl, 'size':size})

import json
f = open("samples.json", "w")
print>>f, json.dumps(ds)

#print ds
