#!/bin/bash

DOMAINNAME=`hostname -d`
if [ $DOMAINNAME == sdfarm.kr ]; then
    XRDHOST=cms-xrdr.sdfarm.kr
    XRDBASE=/cms/data/xrd
elif [ $DOMAINNAME == sscc.uos.ac.kr ]; then
    XRDHOST=uosaf0007.sscc.uos.ac.kr
    XRDBASE=/cms
elif [ $DOMAINNAME == cern.ch ]; then
    XRDHOST=eoscms
    XRDBASE=""
fi

xrd $XRDHOST ls $XRDBASE/$1
