#!/bin/bash

if [ `hostname -d` == sdfarm.kr ]; then
    XRDHOST=cms-xrdr.sdfarm.kr
    XRDBASE=/cms/data/xrd
elif [ `hostname -d` == sscc.uos.ac.kr ]; then
    XRDHOST=uosaf0007.sscc.uos.ac.kr
    XRDBASE=/cms
fi

xrd $XRDHOST ls $XRDBASE/$1
